<?php

// autoload_static.php @generated by Composer

namespace Tangram\Autoload;

class ComposerStaticInitFilesAutoload
{
    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {

        }, null, ClassLoader::class);
    }
}
