<?php
/**
 * Author: garming
 * Date: 2018/4/6
 * Time: 11:10
 */

namespace Tangram\AutoGenerator;


class AutoLoaderGenerator extends BaseGenerator
{
    public function __construct()
    {
        $this->fileName = "autoload_real.php";
    }
    public function generate($absolutePathPerfix)
    {
        $className = "TangramAutoloaderInit".md5($absolutePathPerfix.time());
        $this->write($absolutePathPerfix,$this->autoload_real_fileContent($className));
        $this->writeAutoLoad($absolutePathPerfix,$this->autoload_fileContent($className));
    }
    private function autoload_real_fileContent($str){
        return <<<"EOF"
<?php
include __DIR__.DIRECTORY_SEPARATOR."autoload_router_map.php";
include __DIR__.DIRECTORY_SEPARATOR."autoload_permission_map.php";
include __DIR__.DIRECTORY_SEPARATOR."autoload_classmap.php";
include __DIR__.DIRECTORY_SEPARATOR."autoload_auth_map.php";
include __DIR__.DIRECTORY_SEPARATOR."autoload_views_path.php";

class {$str} {
    public static function getLoader(){
        return;
    }
}
EOF;
    }
    private function autoload_fileContent($str){
        return <<<"EOF"
<?php

// autoload.php @generated by Tangram

require_once __DIR__ . '/auto-tangram' . '/autoload_real.php';

return {$str}::getLoader();
EOF;
    }

}