<?php
/**
 * Created by PhpStorm.
 * User: garming
 * Date: 2017/3/13
 * Time: 20:22
 */

namespace Tangram\AutoFile;


class AutoLoadFile
{
    const NAME = "autoload.php";

    private static function file($md5)
    {
        return <<<"EOF"
<?php

// autoload.php @generated by Tangram

require_once __DIR__ . '/auto-tangram' . '/autoload_real.php';

return TangramAutoloaderInit{$md5}::getLoader();
EOF;
    }

    public static function generate(string $md5)
    {
        $name = DefaultDir::tangramSavePath() . DIRECTORY_SEPARATOR . self::NAME;
        File::create($name, self::file($md5));
    }
}